.PHONY: gen-auth
gen-auth:
	@kitex -module "github.com/wifi32767/TikTokMall" -I ../idl ../idl/auth.proto

.PHONY: gen-user
gen-user:
	@kitex -module "github.com/wifi32767/TikTokMall" -I ../idl ../idl/user.proto

.PHONY: gen-product
gen-product:
	@kitex -module "github.com/wifi32767/TikTokMall" -I ../idl ../idl/product.proto

.PHONY: gen-cart
gen-cart:
	@kitex -module "github.com/wifi32767/TikTokMall" -I ../idl ../idl/cart.proto

.PHONY: gen-order
gen-order:
	@kitex -module "github.com/wifi32767/TikTokMall" -I ../idl ../idl/order.proto