definitions:
  handler.addItemReq:
    properties:
      item:
        $ref: '#/definitions/handler.cartItem'
      userid:
        type: integer
    required:
    - item
    - userid
    type: object
  handler.cartItem:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    required:
    - product_id
    - quantity
    type: object
  handler.errorReturn:
    properties:
      error:
        type: string
    type: object
  handler.idInput:
    properties:
      id:
        type: integer
    required:
    - id
    type: object
  handler.productCreateInput:
    properties:
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      name:
        type: string
      picture:
        type: string
      price:
        type: number
    required:
    - description
    - name
    - picture
    - price
    type: object
  handler.productListInput:
    properties:
      category_name:
        type: string
      page:
        type: integer
      pagesize:
        type: integer
    required:
    - page
    - pagesize
    type: object
  handler.registerInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  handler.searchInput:
    properties:
      query:
        type: string
    required:
    - query
    type: object
  handler.simpleProduct:
    properties:
      categories:
        items:
          type: string
        type: array
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      picture:
        type: string
      price:
        type: number
    required:
    - id
    type: object
  handler.updateInput:
    properties:
      new_password:
        type: string
      old_password:
        type: string
      username:
        type: string
    required:
    - new_password
    - old_password
    - username
    type: object
  handler.userIdReq:
    properties:
      userid:
        type: integer
    required:
    - userid
    type: object
  handler.useridInput:
    properties:
      userid:
        type: integer
    required:
    - userid
    type: object
  test_handler.errorReturn:
    properties:
      error:
        type: string
    type: object
  test_handler.tokenInput:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  test_handler.useridInput:
    properties:
      userid:
        type: integer
    required:
    - userid
    type: object
  test_handler.verifyOutput:
    properties:
      res:
        type: boolean
      userid:
        type: integer
    type: object
info:
  contact: {}
paths:
  /cart/additem:
    post:
      description: 添加商品到指定用户的购物车
      parameters:
      - description: 商品和用户信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.addItemReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 添加商品到购物车
      tags:
      - cart
  /cart/empty:
    post:
      description: 清空指定用户的购物车
      parameters:
      - description: 用户id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.userIdReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 清空购物车
      tags:
      - cart
  /cart/get:
    get:
      description: 获取指定用户的购物车中的商品
      parameters:
      - description: 用户id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.userIdReq'
      produces:
      - application/json
      responses:
        "200":
          description: 购物车中的商品
          schema:
            items:
              $ref: '#/definitions/handler.cartItem'
            type: array
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 获取购物车
      tags:
      - cart
  /product/create:
    post:
      description: 创建一个新的商品
      parameters:
      - description: 商品信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.productCreateInput'
      produces:
      - application/json
      responses:
        "200":
          description: 商品id
          schema:
            $ref: '#/definitions/handler.idInput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 创建商品
      tags:
      - product
  /product/delete:
    delete:
      description: 删除商品
      parameters:
      - description: 商品id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.idInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 删除商品
      tags:
      - product
  /product/get:
    get:
      description: 获取单个商品信息
      parameters:
      - description: 商品id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.idInput'
      produces:
      - application/json
      responses:
        "200":
          description: 商品信息
          schema:
            $ref: '#/definitions/handler.simpleProduct'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 获取商品信息
      tags:
      - product
  /product/list:
    get:
      description: 获取指定类别的商品列表，不指定类别返回全部商品的列表
      parameters:
      - description: 商品列表信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.productListInput'
      produces:
      - application/json
      responses:
        "200":
          description: 商品列表
          schema:
            $ref: '#/definitions/handler.productListInput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 商品列表
      tags:
      - product
  /product/search:
    get:
      description: 搜索在名字和描述中含有关键词的商品
      parameters:
      - description: 搜索关键词
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.searchInput'
      produces:
      - application/json
      responses:
        "200":
          description: 商品信息
          schema:
            $ref: '#/definitions/handler.simpleProduct'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 商品搜索
      tags:
      - product
  /product/update:
    put:
      description: 更新商品信息
      parameters:
      - description: 商品信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.simpleProduct'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 更新商品信息
      tags:
      - product
  /test/auth/delete:
    get:
      description: 删除一个token，即退出该用户在该机器上的登录
      parameters:
      - description: token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/test_handler.tokenInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
      summary: 删除token
      tags:
      - test/auth
  /test/auth/deleteall:
    get:
      description: 删除一个用户的所有token，即退出该用户在所有机器上的登录
      parameters:
      - description: token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/test_handler.useridInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
      summary: 删除所有token
      tags:
      - test/auth
  /test/auth/deliver:
    get:
      description: 对于给定的userid，为它分发一个token
      parameters:
      - description: 用户id
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/test_handler.useridInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/test_handler.tokenInput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
      summary: 获取token
      tags:
      - test/auth
  /test/auth/verify:
    get:
      description: 验证一个token是否有效，以及属于哪个用户。会自动为token续期
      parameters:
      - description: token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/test_handler.tokenInput'
      produces:
      - application/json
      responses:
        "200":
          description: 结果
          schema:
            $ref: '#/definitions/test_handler.verifyOutput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/test_handler.errorReturn'
      summary: 验证token
      tags:
      - test/auth
  /user/delete:
    delete:
      description: 删除一个账户
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 删除账户
      tags:
      - user
  /user/login:
    post:
      description: 登录一个账户
      parameters:
      - description: 登录信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.registerInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 登录
      tags:
      - user
  /user/logout:
    post:
      description: 登出一个账户
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 登出
      tags:
      - user
  /user/register:
    post:
      description: 注册一个新的账户
      parameters:
      - description: 注册信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.registerInput'
      produces:
      - application/json
      responses:
        "200":
          description: 用户id
          schema:
            $ref: '#/definitions/handler.useridInput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 注册账户
      tags:
      - user
  /user/update:
    put:
      description: 修改一个账户的密码
      parameters:
      - description: 修改信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.updateInput'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 修改密码
      tags:
      - user
swagger: "2.0"
