definitions:
  handler.errorReturn:
    properties:
      error:
        type: string
    type: object
  handler.tokenInput:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  handler.useridInput:
    properties:
      userid:
        type: integer
    required:
    - userid
    type: object
  handler.verifyOutput:
    properties:
      res:
        type: boolean
      userid:
        type: integer
    type: object
info:
  contact: {}
paths:
  /test/auth/delete:
    get:
      description: 删除一个token，即退出该用户在该机器上的登录
      parameters:
      - description: token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.tokenInput'
      produces:
      - application/json
      responses:
        "200":
          description: 空
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 删除token
      tags:
      - test/auth
  /test/auth/deleteall:
    get:
      description: 删除一个用户的所有token，即退出该用户在所有机器上的登录
      parameters:
      - description: token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.useridInput'
      produces:
      - application/json
      responses:
        "200":
          description: 空
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 删除所有token
      tags:
      - test/auth
  /test/auth/deliver:
    get:
      description: 对于给定的userid，为它分发一个token
      parameters:
      - description: 用户id
        in: body
        name: userid
        required: true
        schema:
          $ref: '#/definitions/handler.useridInput'
      produces:
      - application/json
      responses:
        "200":
          description: token
          schema:
            $ref: '#/definitions/handler.tokenInput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 获取token
      tags:
      - test/auth
  /test/auth/verify:
    get:
      description: 验证一个token是否有效，以及属于哪个用户。会自动为token续期
      parameters:
      - description: token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.tokenInput'
      produces:
      - application/json
      responses:
        "200":
          description: 结果
          schema:
            $ref: '#/definitions/handler.verifyOutput'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/handler.errorReturn'
      summary: 验证token
      tags:
      - test/auth
swagger: "2.0"
